apiVersion: v1
kind: Service
metadata:
  name: {{ include "workout-timer.fullname" . }}
  labels:
    {{- include "workout-timer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "workout-timer.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
